randomfood/urls.py
from django.conf.urls import url
from . import views

app_name = 'randomfood'
urlpatterns = [
    url(r'^$', views.fill_detail, name='fill_detail'),
    url(r'^random_food_by_type$', views.random_food_by_type, name='random_food_by_type'),
    url(r'^edit_list$', views.edit_list, name='edit_list'),
    url(r'^edit_option$', views.edit_option, name='edit_option'),
    url(r'^add_list/(?P<food_id>[0-9]+)/$', views.add_list, name='add_list'),
    url(r'^del_list/(?P<food_id>[0-9]+)/$', views.del_list, name='del_list'),
    ]

whattoeat/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^', include('randomfood.urls')),
    url(r'^admin/', admin.site.urls),
]

randomfood/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
    
@python_2_unicode_compatible  # only if you need to support Python 2
class Food(models.Model):
    food_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.food_type

@python_2_unicode_compatible  # only if you need to support Python 2
class Menu(models.Model):
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    food_cal = models.IntegerField(default=0)
    food_name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.food_name
    
    

randomfood/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Food,Menu
import random


    
def fill_detail(request):
    lists = Food.objects.order_by('pub_date')
    context = {'lists':lists}
    return render(request, 'randomfood/fill_detail_page.html',context)
    
def random_food_by_type(request):
    food_id = request.POST['type']
    food_type = Food.objects.get(pk=food_id)
    menu_set = food_type.menu_set.all()
    result_id = random.randrange(1,len(menu_set),1)
    menu =  menu_set[result_id]
    cal = menu_set[result_id].food_cal
    context = {'menu':menu,'cal':cal}
    return render(request, 'randomfood/detail_page.html',context)

def edit_list(request):
    lists = Food.objects.order_by('pub_date')
    context = {'lists':lists}
    return render(request, 'randomfood/edit_page.html',context)
    
def edit_option(request):
    lists = Food.objects.order_by('pub_date')
    food_id = request.POST['type']
    food_type = Food.objects.get(pk=food_id)
    food_type_text = food_type.food_text
    menu_set = food_type.menu_set.all()
    
    context = {'menu_set':menu_set, 'food_type_text':food_type_text, 'food_id':food_id}
    return render(request, 'randomfood/option_page.html',context)

def add_list(request,food_id):
    lists = Food.objects.order_by('pub_date')
    food_type = Food.objects.get(pk=food_id)
    food_type_text = food_type.food_text
    menu_set = food_type.menu_set.all()

    name = request.POST['menu_name']
    cal = request.POST['cal']
    q = Food.objects.get(pk=food_id)
    q.menu_set.create(food_cal=cal,food_name=name)
    q.save()
    
    context = {'menu_set':menu_set, 'food_type_text':food_type_text, 'food_id':food_id}
    return render(request, 'randomfood/option_page.html',context)

def del_list(request,food_id):
    food_type = Food.objects.get(pk=food_id)
    food_type_text = food_type.food_text
    menu_id = request.POST['menu_id']
    menu_set = food_type.menu_set.all()
    
    get_menu = Menu.objects.get(id=menu_id)
    get_menu.delete()
    
    context = {'menu_set':menu_set, 'food_type_text':food_type_text, 'food_id':food_id}
    return render(request, 'randomfood/option_page.html',context)

randomfood/templates/randomfood/detail_page.html
{% load static %}
<html>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'randomfood/detail.css' %}" />
    <title>Welcome to Random_food</title>
</head>
<body>
<center>
<div class="head_div">
<h1>{{menu}}({{cal}}kCals)</h1>
</div>
<br><br><br><br> 

<div class="button_div">
<h1 class="button"><u>Not Satisfy?</u></h1>

<form>
<INPUT TYPE="button" onClick="history.go(0)" VALUE="TRY AGAIN!">
</form>

<form action="{% url 'randomfood:fill_detail'%}">
<input type="submit" value="Go Back!" />
</form>

</div>

</body>
</html>

randomfood/templates/randomfood/edit_page.html
{% load static %}
<html>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'randomfood/edit.css' %}" />
    <title>Edit lists of menu</title>
</head>
<body>
<center>
<div class="head_div">
<h1><u>Edit List</u></h1>
</div>
<br><br><br><br>
</div>

<div class="button_div">
<h1><u>Choose one to edit</u></h1>
<form  action="{% url 'randomfood:edit_option' %}" method="post">
{% csrf_token %}
{% for food in lists %}
<input type="radio" name="type" value="{{food.id}}" required/>{{food.food_text}}<br>
{% endfor %}<br><br>
<input type="submit" value="Edit">
</form>
<form>
<INPUT TYPE="button" onClick="history.go(-1)" VALUE="Back">
</form>
</div>
</body>
</html>

randomfood/templates/randomfood/fill_detail_page.html
{% load static %}
<html>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'randomfood/fill_data.css' %}" />
    <title>Fill the information</title>
</head>
<body>
<center>
<div class="head_div">
<h1>Good food, good health.</h1>
</div>
<br><br><br><br> 
    
<div align="left" class="button_div">
<h1 class="button"><u>Choose one</u></h1>
<form  action="{% url 'randomfood:random_food_by_type' %}" method="post">
{% csrf_token %}
{% for food in lists %}
<input id="choice" type="radio" name="type" value="{{food.id}}" required/>{{food.food_text}}<br>
{% endfor %}<br><br>
<center>
<input id="submit" type="submit" value="Choose" >

</form>
<h1 class="button"><u>Click to Edit</u></h1>
<form  action="{% url 'randomfood:edit_list' %}">
<input id="submit" type="submit" value="Edit" >
</form>
</div>

</body>
</html>

randomfood/templates/randomfood/home.html
{% load static %}
<html>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'randomfood/home.css' %}" />
    <title>Welcome to Random_food</title>
</head>
<body>
<center>
<div class="head_div">
<h1>Don't know what to eat?</h1>
</div>
<br><br><br><br> 

<div class="button_div">
<h1 class="button">Just click</h1>

<form id="button_box" action="{% url 'randomfood:fill_detail' %}">
<input type="submit" value="Just Click">
</form>
</div>

</body>
</html>

randomfood/templates/randomfood/option_page.html
{% load static %}
<html>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'randomfood/edit.css' %}" />
    <title>Choose menu to edit</title>
</head>
<body>
<center>
<div class="head_div">
<h1><u>Select to delete</u></h1>
</div>
<br><br><br><br> 

<div align="left" class="button_div">
<center>
<h1 class="button"><u>{{food_type_text}}</u></h1>
</center>
<form action="{% url 'randomfood:del_list' food_id %}" method="post">
{% csrf_token %}
{% for menu in menu_set %}
<input type="radio" name="menu_id" value={{menu.id}} required/>{{menu.food_name}} ({{menu.food_cal}} Kcal) <br>
{% endfor %}<br><br>
<input type="submit" value="Delete" >
</form>
<center>
<h1>Or add new one</h1>
</center>

<form action="{% url 'randomfood:add_list' food_id %}" method="post">
{% csrf_token %}
ชื่ออาหาร  <input type="text" name="menu_name" required/><br>
ปริมาณแคลลอรี่  <input type="number" name="cal" required/><br><br>
<input type="submit" value="Add">
</form>
<center>
<form action="{% url 'randomfood:edit_list'%}">
<input type="submit" value="Go Back!" >
</form>


</div>

</body>
</html>